Update pom.xml
Added dependency to fix runtime error:

java.util.ServiceConfigurationError: javax.xml.transform.TransformerFactory: Provider org.apache.xalan.processor.TransformerFactoryImpl not a subtype
       at java.util.ServiceLoader.fail(ServiceLoader.java:239)
       at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
       at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
       at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
       at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
       at javax.xml.transform.FactoryFinder$1.run(FactoryFinder.java:280)
       at java.security.AccessController.doPrivileged(Native Method)
       at javax.xml.transform.FactoryFinder.findServiceProvider(FactoryFinder.java:275)
Caused: java.lang.RuntimeException: Provider for class javax.xml.transform.TransformerFactory cannot be created
       at javax.xml.transform.FactoryFinder.findServiceProvider(FactoryFinder.java:294)
       at javax.xml.transform.FactoryFinder.find(FactoryFinder.java:251)
       at javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:106)
       at hudson.plugins.jobConfigHistory.JobConfigHistoryBaseAction.<init>(JobConfigHistoryBaseAction.)